### ISSUE TITLE
execution keeps failing 

### ISSUE THREAD

**Issue by Sripaad** [iainharfield/flogo#1]
![screenshot from 2018-12-28 13-09-50](https://user-images.githubusercontent.com/27012182/50507092-f781c480-0aa1-11e9-8d84-52e03f5b35bc.png)

**Comment by iainharfield** [comment]
Hi,  It looks like you are using the example flow which is triggered from an http event.  What I am doing is triggering from my chrome/safari browser with this syntax on my MacBook: 
http://localhost:9121/qos/speed?cmd=/Users/iain/Downloads/test01.sh&params=xxx yyy
or on my linux (ubuntu) server using Chrome:
http://localhost:9121/qos/speed?cmd=/home/iain/Downloads/test01.sh&params=xxx yyy
this seems to be working fine.   I have NOT tried windows at all.

The only way I have reproduced the error you see is if the syntax is wrong in a way it can't parse the cmd field.   

I'm also a bit new to flogo and go so apologies if code is not so robust.  Can you check your browser syntax that triggers the flow.

Many thanks
Iain

**Comment by Sripaad** [comment]
Thanks Ian, this seems to be working 
ill close the issue

**Comment by iainharfield** [comment]
Fantastic, thanks!
